name: Update Gold Prices CSV

on:
  schedule:
    - cron: '0 * * * *'  # كل ساعة
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install axios

      - name: Run Update Script
        run: node update-csv.js
        env:
          API_KEY: ${{ secrets.METALS_API_KEY }}

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.csv
          git commit -m "Update gold prices automatically"
          git push
